import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "CamerMap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,    
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>{children}<Toaster /></div>
      </body>
    </html>
  );
}
